[business]
e1001 = "参数绑定错误"
e2001 = "检查应用名称错误"
e2002 = "应用名称已存在"
e2003 = "添加应用程序错误"
e2004 = "检查配置名称错误"
e2005 = "配置名称已存在"
e2006 = "添加配置名称错误"
e2007 = "查询应用程序列表错误"
e2008 = "添加应用程序模式错误"
e2009 = "添加应用程序版本错误"
e2010 = "应用程序模式已存在"